age=float(input('How old are you?'))
print(f'On your next birthday, you will be {age+1}')
print()
eggs=float(input('How many cartons of eggs do you have?'))
print(f'You have {eggs*12} eggs')
print()
cook=float(input('How many cookies do you have?'))
people=float(input('How many people are there?'))
print(f'Each person can have {cook/people} cookies.')