cmeal=float(input('What is the cost of a child\'s meal?'))
ameal=float(input('What is the price of an adult\'s meal?'))
children=int(input('How many children are there?'))
adults=int(input('How many adults are there? '))
tax=float(input('What is the sales tax rate?'))
print()

subtotal=(cmeal*children+ameal*adults)
print(f'Subtotal: ${subtotal}')
stax=((tax/100)*subtotal)
print(f'Sales Tax: ${round(stax,2)}')
total=(stax+subtotal)
print(f'Total: ${round(total,2)}')
pay=float(input('What is the payment amount?'))
change=(pay-total)
print(f'${round(change,2)}')